### ISSUE TITLE
stale scan toggle button should not show a plain-text error when not authorized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jakepaulus/collate-network#118]
```
The stale scan toggle button in list_statics() in statics.php should redirect 
to a login page if a user needs to login, or it should be grayed out if the 
user is logged in but doesn't have permissions to it.
```

Original issue reported on code.google.com by `JakePaulus` on 18 Aug 2014 at 11:48

**Comment by jakepaulus** [comment]
Updated the toggle stale-scan functionality to use an AJAX request instead of a normal hyperlink to a new page. This prevents the header(Location: ...) call that dumps a user to the ugly error page.
