### ISSUE TITLE
Editing a field doesn't treat case properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jakepaulus/collate-network#122]
```
What steps will reproduce the problem?
1. Name an object TEST
2. Try to rename the object to Test

What is the expected output? What do you see instead?
The comparison that checks to see whether a real change has been submitted 
doesn't detect the difference in character case. It thinks the two from the 
example are equivalent, and it doesn't save the change.
```

Original issue reported on code.google.com by `JakePaulus` on 7 Oct 2014 at 4:42

**Comment by jakepaulus** [comment]
Found this situation to only be the case for block names due to the way the duplicate name check worked. An optimization to avoid doing an UPDATE if the name hadn't changed (the query was NOT case-sensitive) resulted in no UPDATE when only a case change was made.
